// Generated by CoffeeScript 1.3.3
var compress, initialize, only_elements;

compress = function(item) {
  var i, result, _i, _len;
  result = "";
  if (item === null || item === void 0) {
    return "";
  }
  if (typeof item === "string") {
    return item;
  } else if (item.length && item.length > 0) {
    for (_i = 0, _len = item.length; _i < _len; _i++) {
      i = item[_i];
      result += compress(i);
    }
  }
  return result;
};

only_elements = function(element) {
  return element.type;
};

initialize = function() {
  var define_element, element, elements, get_value, name, _results;
  get_value = function(value, type) {
    if (type === 'compress') {
      return compress(value);
    }
    return value;
  };
  define_element = function(name, element) {
    var new_class;
    new_class = function() {
      var args, key, type, x;
      args = Array.prototype.slice.call(arguments);
      x = 0;
      this.type = name.toLowerCase();
      for (key in element) {
        type = element[key];
        if (x > args.length) {
          break;
        }
        this[key] = args[x++];
      }
      return this;
    };
    new_class.prototype.constructor = new_class;
    return global[name] = new_class;
  };
  elements = {
    Arguments: {
      expressions: 'list'
    },
    Block: {
      elements: 'string'
    },
    Class_Definition: {
      name: 'compress',
      block: 'list'
    },
    Class_Block: {
      elements: 'string'
    },
    Code: {
      elements: 'list'
    },
    Control: {
      name: 'string',
      condition: 'string',
      body: 'list'
    },
    Function_Definition: {
      name: 'compress',
      parameters: 'string',
      block: 'list'
    },
    Invoke_Function: {
      name: 'compress',
      "arguments": 'list'
    },
    Literal_String: {
      text: 'string'
    },
    Method_Definition: {
      name: 'compress',
      parameters: 'string',
      block: 'list',
      constructor: 'bool'
    },
    Parameter: {
      name: 'string',
      default_value: 'string'
    },
    Parameters: {
      variables: 'list'
    },
    Property: {
      variable: 'string',
      value: 'string'
    },
    Variable: {
      name: 'compress',
      children: 'compress',
      index: 'compress'
    }
  };
  _results = [];
  for (name in elements) {
    element = elements[name];
    _results.push(define_element(name, element));
  }
  return _results;
};

initialize();
